### ISSUE TITLE
PiKVM support

### ISSUE THREAD

**Issue by arch1mede** [LibVNC/libvncserver#476] opened 2021-07-16 23:07 UTC
Hi,

I support a small community called PiKVM and would love to see this work towards the vnc server that's provided. Here is what the author told me why its not supported:

_Guacamole is unsupported - Incorrectly implements vencrypt, no JPEG compression._

**Comment by bk138** [comment] 2021-07-17 08:25
Uh, can you provide some more context what this feature request is about?

**Comment by arch1mede** [comment] 2021-07-19 11:24
Not sure what else to add other than a request for it to work with this project. Looks like the author started to but then it fizzled out for some reason. See [here](https://github.com/LibVNC/libvncserver/issues/458)

**Comment by bk138** [comment] 2021-07-19 11:29
> Not sure what else to add other than a request for it to work with this project. Looks like the author started to but then it fizzled out for some reason. See [here](https://github.com/LibVNC/libvncserver/issues/458)

Well, we would like to know what PiKVM actually is and what feature exactly is requested.

**Comment by arch1mede** [comment] 2021-07-19 11:39
[PiKVM](https://pikvm.org/) This is a IP KVM that had a vnc server functionality, we have users looking for this to work within Guacamole but its currently not working per the verbiage in the original message, I am not sure if this would be considered a dupe as he was looking for specifics and then roping in an author that became unresponsive.

**Comment by bk138** [comment] 2021-07-19 11:51
So this issue is about "Let LibVNCServer support Guacamole"? By which means, i.e. what should be done? What exactly does not work, what should work?

**Comment by arch1mede** [comment] 2021-07-19 11:59
Please provide what you'd want to see for logs, I don't have anything other than what the author has provided. libvnc does not connect or display, does not give an error at least through the web gui, as far as I can tell.

**Comment by bk138** [comment] 2021-07-19 12:11
Please see https://www.softwaretestinghelp.com/how-to-write-good-bug-report/ and provide the needed info.

**Comment by arch1mede** [comment] 2021-07-19 12:19
[This](https://www.softwaretestinghelp.com/how-to-write-good-bug-report/) isn't specific to libvnc but just a general how to report bugs. I don't know how else to word this request other than getting it to work. It could be tagged as a bug because it will not connect, it could be tagged as a feature because it should support the vnc server. I am really looking for support to get this working.

If you or anyone could provide the commands or where the logs you'd want to see attached here, then I can get them. I am currently running this in a docker so I do not know where to get this information for you.

**Comment by bk138** [comment] 2021-07-19 12:26
We simply need more info for tackling this. How to reproduce, with what versions of which software, what to look for etc.

**Comment by mdevaev** [comment] 2021-07-21 14:29
Sup. Pi-KVM's author here. 

The main problem with support is related to this task: #458. It describes the problem in detail and suggests solutions.

**Comment by bk138** [comment] 2021-07-23 16:47
> Sup. Pi-KVM's author here.
> 
> The main problem with support is related to this task: #458. It describes the problem in detail and suggests solutions.

@mdevaev Alright, thanks for the info! So we can close this one as a dupe of #458?

**Comment by mdevaev** [comment] 2021-07-23 16:49
Okay, but please add information about this to that issue.

**Comment by bk138** [comment] 2021-07-23 18:13
> Okay, but please add information about this to that issue.

If you mean that this one's a dupe of #458, that's done automatically.

**Closed by bk138** 2021-07-23 18:13 UTC
Labels: feature-request, response-needed
