### ISSUE TITLE
 Ultra VNC 1.2.2.3 connect examples_simple, show "rfbProcessNewConnection: error in select"

### ISSUE THREAD

**Issue by GavinToHill** [LibVNC/libvncserver#344] opened 2019-10-27 07:42 UTC
If you'd like to put out an incentive for fixing this bug, you can do so at https://issuehunt.io/r/LibVNC/libvncserver

**Describe the bug**
Ultra VNC 1.2.2.3 viewer connect examples_simple, show "rfbProcessNewConnection: error in select",

**To Reproduce**
1. cmake and build with vs2019
2. run examples_simple
3. run Ultra VNC 1.2.2.3 viewer, examples_simple shows "rfbProcessNewConnection: error in select"

**Expected Behavior**

**Logs/Backtraces**

**Your environment (please complete the following information):**
 - OS and version: windows 10
 - Compiler and version: Visual Studio 2019

**Additional context**
the following is log :
7/10/2019 15:45:31 Listening for VNC connections on TCP port 5903
27/10/2019 15:45:58 rfbProcessNewConnection: error in select: 27/10/2019 15:45:58 rfbProcessNewConnection: error in select: (null)
27/10/2019 15:45:58 rfbProcessNewConnection: error in select: (null)
27/10/2019 15:45:59 rfbProcessNewConnection: error in select: (null)
27/10/2019 15:45:59 rfbProcessNewConnection: error in select: (null)
27/10/2019 15:45:59 rfbProcessNewConnection: error in select: (null)
27/10/2019 15:46:00 rfbProcessNewConnection: error in select: (null)
27/10/2019 15:46:00 rfbProcessNewConnection: error in select: (null)

**Comment by bk138** [comment] 2019-10-27 12:23
The Windows builds are not functioning at the moment, we want to fix this for 0.9.13. This is a mre dupe of #165, please subscribe there.

**Closed by bk138** 2019-10-27 12:23 UTC
Labels: bug, platform-windows

**Comment by GavinToHill** [comment] 2019-10-28 12:40
> The Windows builds are not functioning at the moment, we want to fix this for 0.9.13. This is a mere dupe of #165, please subscribe there.

ok, thanks, when will 0.9.13 publish, andy plan?

**Comment by bk138** [comment] 2019-10-28 16:02
Hard to say, day job taking up a lotta time.
