### ISSUE TITLE
cannot get ABS_X info, Invalid argument

### ISSUE THREAD

**Issue by f0lg0** [LibVNC/libvncserver#637] opened 2024-11-07 09:58 UTC
I've managed to correctly compile the library for Android 9 and pushed the `androidvncserver` binary to the device but when I run it in a **root** shell I get the following output:
```
Initializing framebuffer device /dev/graphics/fb0...
xres=1920, yres=1080, xresv=1920, yresv=2160, xoffs=0, yoffs=0, bpp=32
Initializing keyboard device /dev/input/event3 ...
Initializing touch device /dev/input/event1 ...
cannot get ABS_X info, Invalid argument
```

I saw similar [issues](https://github.com/LibVNC/libvncserver/issues/184) but they were closed.
I need a simple vnc server binary that I can run at device boot, I've also tried the `droidVNC-ng` app which works fine but even with the checkbox set to run on boot it doesn't start upon booting up the device and I have to manually open the app.
I'm open to any kind of suggestion, what I'd like is a binary that I can run at startup.
Thanks

**Comment by bk138** [comment] 2024-11-07 10:21
`androidvncserver` is very much just a demo and uses legacy APIs, so there's no guarantee things are working as intended. I recommend to use droidVNC-NG, we should fix start-on-boot for that one together, so feel free to file an issue there (need logcat output!).

**Comment by bk138** [comment] 2024-11-07 10:23
Dupe of #184 anyway, which I'll re-open.

**Closed by bk138** 2024-11-07 10:23 UTC
Labels: platform-android, question

**Comment by f0lg0** [comment] 2024-11-07 10:29
> `androidvncserver` is very much just a demo and uses legacy APIs, so there's no guarantee things are working as intended. I recommend to use droidVNC-NG, we should fix start-on-boot for that one together, so feel free to file an issue there (need logcat output!).

@bk138 is droidVNC-NG the only option or is there a simple binary I can start upon boot? Als, how would I grab the logcat upon booting? I don't think `adb logcat` would work in this case but I'm not sure, also do you happen to know which filter can I use to just see the droidVNC lgos? I've tried multiple of them but I just get not results. Here's some output I'm getting when simply opening the app and clicking start

```
11-07 10:07:52.139  3526  3784 I ActivityManager: START u0 {flg=0x10000000 cmp=net.christianbeier.droidvnc_ng/.MediaProjectionRequestActivity} from uid 10045
11-07 10:07:52.281  4198  4198 W Defaults: /storage/emulated/0/Android/data/net.christianbeier.droidvnc_ng/files/defaults.json (No such file or directory)
11-07 10:07:52.310  4198  4198 I droidvnc-ng (native): Listening for VNC connections on TCP port 5900
11-07 10:07:52.311  4198  4198 I droidvnc-ng (native): Listening for VNC connections on TCP6 port 5900
11-07 10:07:52.311  4198  4198 I droidvnc-ng (native): Listening for HTTP connections on TCP port 5800
11-07 10:07:52.311  4198  4198 I droidvnc-ng (native):   URL http://localhost:5800
11-07 10:07:52.311  4198  4198 I droidvnc-ng (native): Listening for HTTP connections on TCP6 port 5800
11-07 10:07:52.311  4198  4198 I droidvnc-ng (native):   URL http://localhost:5800
11-07 10:07:52.311  4198  4198 I droidvnc-ng (native): vncStartServer: successfully started
11-07 10:07:52.354  4198  4198 W Defaults: /storage/emulated/0/Android/data/net.christianbeier.droidvnc_ng/files/defaults.json (No such file or directory)
11-07 10:07:52.400  4198  4198 W Defaults: /storage/emulated/0/Android/data/net.christianbeier.droidvnc_ng/files/defaults.json (No such file or directory)
11-07 10:07:52.450  4198  4198 W Defaults: /storage/emulated/0/Android/data/net.christianbeier.droidvnc_ng/files/defaults.json (No such file or directory)
11-07 10:07:52.453  3526  3545 I DisplayManagerService: Display device added: DisplayDeviceInfo{"droidVNC-NG": uniqueId="virtual:net.christianbeier.droidvnc_ng,10045,droidVNC-NG,0", 1442 x 811, modeId 4, defaultModeId 4, supportedModes [{id=4, width=1442, height=811, fps=60.0}], colorMode 0, supportedColorModes [0], HdrCapabilities null, density 213, 213.0 x 213.0 dpi, appVsyncOff 0, presDeadline 16666666, touch NONE, rotation 0, type VIRTUAL, state ON, owner net.christianbeier.droidvnc_ng (uid 10045), FLAG_PRIVATE, FLAG_PRESENTATION}
11-07 10:07:52.481  3526  3526 E NotificationService: Muting recently noisy 0|net.christianbeier.droidvnc_ng|11|null|10045
11-07 10:07:52.511  4198  4198 I droidvnc-ng (native): vncNewFramebuffer: allocated new framebuffer, 1456x811
11-07 10:07:52.544  4198  4198 I chatty  : uid=10045(net.christianbeier.droidvnc_ng) identical 4 lines
11-07 10:08:09.345  4198  5161 E droidvnc-ng (native): httpCheckFds: select: Bad file descriptor
11-07 10:08:09.346  4198  4198 I droidvnc-ng (native): vncStopServer: successfully stopped
11-07 10:08:09.379  3526  3796 I DisplayManagerService: Display device removed: DisplayDeviceInfo{"droidVNC-NG": uniqueId="virtual:net.christianbeier.droidvnc_ng,10045,droidVNC-NG,0", 1442 x 811, modeId 4, defaultModeId 4, supportedModes [{id=4, width=1442, height=811, fps=60.0}], colorMode 0, supportedColorModes [0], HdrCapabilities null, density 213, 213.0 x 213.0 dpi, appVsyncOff 0, presDeadline 16666666, touch NONE, rotation 0, type VIRTUAL, state ON, owner net.christianbeier.droidvnc_ng (uid 10045), FLAG_PRIVATE, FLAG_PRESENTATION}
11-07 10:08:10.002  4198  4198 W Defaults: /storage/emulated/0/Android/data/net.christianbeier.droidvnc_ng/files/defaults.json (No such file or directory)
11-07 10:08:10.252  4198  4198 W Defaults: /storage/emulated/0/Android/data/net.christianbeier.droidvnc_ng/files/defaults.json (No such file or directory)
11-07 10:08:10.253  3526  3545 I ActivityManager: START u0 {flg=0x10000000 cmp=net.christianbeier.droidvnc_ng/.InputRequestActivity (has extras)} from uid 10045
11-07 10:08:10.291  4198  4198 W Defaults: /storage/emulated/0/Android/data/net.christianbeier.droidvnc_ng/files/defaults.json (No such file or directory)
11-07 10:08:10.295  4198  4198 W Defaults: /storage/emulated/0/Android/data/net.christianbeier.droidvnc_ng/files/defaults.json (No such file or directory)
11-07 10:08:10.318  3526  3796 I ActivityManager: START u0 {flg=0x10000000 cmp=net.christianbeier.droidvnc_ng/.WriteStorageRequestActivity (has extras)} from uid 10045
11-07 10:08:10.350  4198  4198 W Defaults: /storage/emulated/0/Android/data/net.christianbeier.droidvnc_ng/files/defaults.json (No such file or directory)
11-07 10:08:10.354  4198  4198 W Defaults: /storage/emulated/0/Android/data/net.christianbeier.droidvnc_ng/files/defaults.json (No such file or directory)
11-07 10:08:10.374  3526  3784 I ActivityManager: START u0 {flg=0x10000000 cmp=net.christianbeier.droidvnc_ng/.MediaProjectionRequestActivity} from uid 10045
11-07 10:08:10.500  4198  4198 W Defaults: /storage/emulated/0/Android/data/net.christianbeier.droidvnc_ng/files/defaults.json (No such file or directory)
11-07 10:08:10.521  4198  4198 I droidvnc-ng (native): Listening for VNC connections on TCP port 5900
11-07 10:08:10.522  4198  4198 I droidvnc-ng (native): Listening for VNC connections on TCP6 port 5900
11-07 10:08:10.522  4198  4198 I droidvnc-ng (native): Listening for HTTP connections on TCP port 5800
11-07 10:08:10.522  4198  4198 I droidvnc-ng (native):   URL http://localhost:5800
11-07 10:08:10.522  4198  4198 I droidvnc-ng (native): Listening for HTTP connections on TCP6 port 5800
11-07 10:08:10.522  4198  4198 I droidvnc-ng (native):   URL http://localhost:5800
11-07 10:08:10.522  4198  4198 I droidvnc-ng (native): vncStartServer: successfully started
11-07 10:08:10.562  4198  4198 W Defaults: /storage/emulated/0/Android/data/net.christianbeier.droidvnc_ng/files/defaults.json (No such file or directory)
11-07 10:08:10.599  4198  4198 W Defaults: /storage/emulated/0/Android/data/net.christianbeier.droidvnc_ng/files/defaults.json (No such file or directory)
11-07 10:08:10.633  4198  4198 W Defaults: /storage/emulated/0/Android/data/net.christianbeier.droidvnc_ng/files/defaults.json (No such file or directory)
11-07 10:08:10.636  3526  3545 I DisplayManagerService: Display device added: DisplayDeviceInfo{"droidVNC-NG": uniqueId="virtual:net.christianbeier.droidvnc_ng,10045,droidVNC-NG,0", 1442 x 811, modeId 5, defaultModeId 5, supportedModes [{id=5, width=1442, height=811, fps=60.0}], colorMode 0, supportedColorModes [0], HdrCapabilities null, density 213, 213.0 x 213.0 dpi, appVsyncOff 0, presDeadline 16666666, touch NONE, rotation 0, type VIRTUAL, state ON, owner net.christianbeier.droidvnc_ng (uid 10045), FLAG_PRIVATE, FLAG_PRESENTATION}
11-07 10:08:10.662  3526  3526 E NotificationService: Muting recently noisy 0|net.christianbeier.droidvnc_ng|11|null|10045
11-07 10:08:10.801  4198  4198 I droidvnc-ng (native): vncNewFramebuffer: allocated new framebuffer, 1456x811
11-07 10:08:10.827  3296  4067 E BufferQueueProducer: [net.christianbeier.droidvnc_ng/net.christianbeier.droidvnc_ng.MediaProjectionRequestActivity#0] disconnect: not connected (req=1)
11-07 10:08:11.564  4198  4198 I droidvnc-ng (native): vncStopServer: successfully stopped
11-07 10:08:11.582  3526  3669 I DisplayManagerService: Display device removed: DisplayDeviceInfo{"droidVNC-NG": uniqueId="virtual:net.christianbeier.droidvnc_ng,10045,droidVNC-NG,0", 1442 x 811, modeId 5, defaultModeId 5, supportedModes [{id=5, width=1442, height=811, fps=60.0}], colorMode 0, supportedColorModes [0], HdrCapabilities null, density 213, 213.0 x 213.0 dpi, appVsyncOff 0, presDeadline 16666666, touch NONE, rotation 0, type VIRTUAL, state ON, owner net.christianbeier.droidvnc_ng (uid 10045), FLAG_PRIVATE, FLAG_PRESENTATION}
11-07 10:28:03.180  4198  4198 W Defaults: /storage/emulated/0/Android/data/net.christianbeier.droidvnc_ng/files/defaults.json (No such file or directory)
11-07 10:28:03.441  4198  4198 W Defaults: /storage/emulated/0/Android/data/net.christianbeier.droidvnc_ng/files/defaults.json (No such file or directory)
11-07 10:28:03.442  3526  3669 I ActivityManager: START u0 {flg=0x10000000 cmp=net.christianbeier.droidvnc_ng/.InputRequestActivity (has extras)} from uid 10045
11-07 10:28:03.454  4198  4239 I ier.droidvnc_n: Waiting for a blocking GC ProfileSaver
11-07 10:28:03.490  4198  4198 W Defaults: /storage/emulated/0/Android/data/net.christianbeier.droidvnc_ng/files/defaults.json (No such file or directory)
11-07 10:28:03.493  4198  4198 W Defaults: /storage/emulated/0/Android/data/net.christianbeier.droidvnc_ng/files/defaults.json (No such file or directory)
11-07 10:28:03.511  3526  3669 I ActivityManager: START u0 {flg=0x10000000 cmp=net.christianbeier.droidvnc_ng/.WriteStorageRequestActivity (has extras)} from uid 10045
11-07 10:28:03.544  4198  4198 W Defaults: /storage/emulated/0/Android/data/net.christianbeier.droidvnc_ng/files/defaults.json (No such file or directory)
11-07 10:28:03.546  4198  4198 W Defaults: /storage/emulated/0/Android/data/net.christianbeier.droidvnc_ng/files/defaults.json (No such file or directory)
11-07 10:28:03.561  3526  3669 I ActivityManager: START u0 {flg=0x10000000 cmp=net.christianbeier.droidvnc_ng/.MediaProjectionRequestActivity} from uid 10045
11-07 10:28:03.671  4198  4198 W Defaults: /storage/emulated/0/Android/data/net.christianbeier.droidvnc_ng/files/defaults.json (No such file or directory)
11-07 10:28:03.694  4198  4198 I droidvnc-ng (native): Listening for VNC connections on TCP port 5900
11-07 10:28:03.695  4198  4198 I droidvnc-ng (native): Listening for VNC connections on TCP6 port 5900
11-07 10:28:03.695  4198  4198 I droidvnc-ng (native): Listening for HTTP connections on TCP port 5800
11-07 10:28:03.695  4198  4198 I droidvnc-ng (native):   URL http://localhost:5800
11-07 10:28:03.695  4198  4198 I droidvnc-ng (native): Listening for HTTP connections on TCP6 port 5800
11-07 10:28:03.695  4198  4198 I droidvnc-ng (native):   URL http://localhost:5800
11-07 10:28:03.695  4198  4198 I droidvnc-ng (native): vncStartServer: successfully started
11-07 10:28:03.717  3296  3296 D SurfaceFlinger: duplicate layer name: changing Surface(name=AppWindowToken{100c9ab token=Token{17a2ffa ActivityRecord{3611225 u0 net.christianbeier.droidvnc_ng/.MediaProjectionRequestActivity t5}}})/@0x5b46e7f - animation-leash to Surface(name=AppWindowToken{100c9ab token=Token{17a2ffa ActivityRecord{3611225 u0 net.christianbeier.droidvnc_ng/.MediaProjectionRequestActivity t5}}})/@0x5b46e7f - animation-leash#1
11-07 10:28:03.732  4198  4198 W Defaults: /storage/emulated/0/Android/data/net.christianbeier.droidvnc_ng/files/defaults.json (No such file or directory)
11-07 10:28:03.771  4198  4198 W Defaults: /storage/emulated/0/Android/data/net.christianbeier.droidvnc_ng/files/defaults.json (No such file or directory)
11-07 10:28:03.800  4198  4198 W Defaults: /storage/emulated/0/Android/data/net.christianbeier.droidvnc_ng/files/defaults.json (No such file or directory)
11-07 10:28:03.804  3526  3545 I DisplayManagerService: Display device added: DisplayDeviceInfo{"droidVNC-NG": uniqueId="virtual:net.christianbeier.droidvnc_ng,10045,droidVNC-NG,0", 1442 x 811, modeId 6, defaultModeId 6, supportedModes [{id=6, width=1442, height=811, fps=60.0}], colorMode 0, supportedColorModes [0], HdrCapabilities null, density 213, 213.0 x 213.0 dpi, appVsyncOff 0, presDeadline 16666666, touch NONE, rotation 0, type VIRTUAL, state ON, owner net.christianbeier.droidvnc_ng (uid 10045), FLAG_PRIVATE, FLAG_PRESENTATION}
11-07 10:28:03.830  3526  3526 E NotificationService: Muting recently noisy 0|net.christianbeier.droidvnc_ng|11|null|10045
11-07 10:28:03.991  4198  4198 I droidvnc-ng (native): vncNewFramebuffer: allocated new framebuffer, 1456x811
11-07 10:28:04.019  3296  3525 E BufferQueueProducer: [net.christianbeier.droidvnc_ng/net.christianbeier.droidvnc_ng.MediaProjectionRequestActivity#0] disconnect: not connected (req=1)
11-07 10:28:05.021  4198  5346 E droidvnc-ng (native): httpCheckFds: select: Bad file descriptor
11-07 10:28:05.023  4198  4198 I droidvnc-ng (native): vncStopServer: successfully stopped
11-07 10:28:05.029  3526  3669 I DisplayManagerService: Display device removed: DisplayDeviceInfo{"droidVNC-NG": uniqueId="virtual:net.christianbeier.droidvnc_ng,10045,droidVNC-NG,0", 1442 x 811, modeId 6, defaultModeId 6, supportedModes [{id=6, width=1442, height=811, fps=60.0}], colorMode 0, supportedColorModes [0], HdrCapabilities null, density 213, 213.0 x 213.0 dpi, appVsyncOff 0, presDeadline 16666666, touch NONE, rotation 0, type VIRTUAL, state ON, owner net.christianbeier.droidvnc_ng (uid 10045), FLAG_PRIVATE, FLAG_PRESENTATION}
```

Grabbed just by running `adb logcat`

**Comment by bk138** [comment] 2024-11-07 11:01
@f0lg0 you can just run `adb logcat` and reboot the device, make sure it adb reconnects on device boot, if not, you have to do adb logcat again manually. Needs a bit of fiddling but I know for a fact that one can get early boot logs with that. Let's discuss over at droidVNC-NG.

**Comment by f0lg0** [comment] 2024-11-07 11:43
> @f0lg0 you can just run `adb logcat` and reboot the device, make sure it adb reconnects on device boot, if not, you have to do adb logcat again manually. Needs a bit of fiddling but I know for a fact that one can get early boot logs with that. Let's discuss over at droidVNC-NG.

Sure, here you go https://github.com/bk138/droidVNC-NG/issues/245 @bk138
