### ISSUE TITLE
client_examples/vnc2mpg.c fails to compile

### ISSUE THREAD

**Issue by j4riv** [LibVNC/libvncserver#272] opened 2018-11-30 20:11 UTC
https://github.com/LibVNC/libvncserver/blob/19b695e9f8372ed5ea7174dc8f8a669e345305b9/client_examples/vnc2mpg.c#L155

Maybe version check is needed?
" vnc2mpg.c:155:50: error: ‘AVStream {aka struct AVStream}’ has no member named ‘codecpar’
     ret = avcodec_parameters_from_context(ost->st->codecpar, ost->enc); "

**Comment by bk138** [comment] 2018-12-01 11:52
maybe. do you have one at hand? 

Am 30. November 2018 21:11:11 MEZ schrieb Jari Vuoksenranta <notifications@github.com>:
>https://github.com/LibVNC/libvncserver/blob/19b695e9f8372ed5ea7174dc8f8a669e345305b9/client_examples/vnc2mpg.c#L155>
>>
>Maybe version check is needed?>
>" vnc2mpg.c:155:50: error: ‘AVStream {aka struct AVStream}’ has no
>member named ‘codecpar’>
> ret = avcodec_parameters_from_context(ost->st->codecpar, ost->enc); ">
>>
>-- >
>You are receiving this because you are subscribed to this thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/LibVNC/libvncserver/issues/272

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by bk138** [comment] 2018-12-28 19:40
This is a dupe of #231, it seems.

**Closed by bk138** 2018-12-28 19:40 UTC
