### ISSUE TITLE
Tight encoding pixel errors on iMX6 platform, both ZLIB and JPEG 

### ISSUE THREAD

**Issue by PT2020-cd** [LibVNC/libvncserver#363] opened 2020-01-07 08:37 UTC
I'm using libvncserver 0.9.12 on a iMX6 platform with Linux kernel 4.9.88. No matter what VNC client I use on my PC the Tight encoding (JPEG and PNG with different quality/compression settings) has some pixel errors. All other encoding types are working well. Pixel errors does mean at least one rect is distorted (only on some screens and always on the same screens and always the same pixel errors). The framebuffer is a 32 bit image with 640x480 pixels without alpha channel.

The function rfbBoolSendRectEncodingTight(rfbClientPtr cl, int x, int y, int w, int h) is called about 5-10 times recoursively depending on the screen. For now I could not locate the problem exactly. The problem only seems to exist when using the release build of libvncserver (-Os). When using a debug build (-O0 -g3) it seems working well.

I there anyone who can confirm?

**Comment by bk138** [comment] 2020-01-07 12:23
Are you using libjpeg-turbo or libjpeg?

**Comment by PT2020-cd** [comment] 2020-01-07 12:29
I'm using this with buildroot and jpeg-turbo-2.0.2 as well as libpng-1.6.37.
Hint: the problem is also when using Tight encoding without JPEG (ZLIB).

**Comment by bk138** [comment] 2020-01-07 12:42
I suggest narrowing down the variuos code paths until you can pinpoint the code in question. After all, it seems like something caused by the compiler, but we might me able to work around that by code changes...

**Comment by PT2020-cd** [comment] 2020-01-07 12:50
I will try to find out more in detail. Is there an explanation about tight encoding in general anywhere (I did not find anything useful in the web)? Most helpful with example.

**Comment by bk138** [comment] 2020-01-07 13:02
Tight encoding mostly means lossy JPEG encoding, so I'm not really sure that there is a ZLIB code path in there....

**Comment by PT2020-cd** [comment] 2020-01-07 13:13
IMHO Tight encoding is dividing the framebuffer into rects. These rects are compressed eighter by JPEG or PNG (ZLIB). The error seems to be in finding/defining the rects because it's the same result when compressed with JPEG (lossy) and PNG (lossless). But without an explanantion how the rects are calculated it's nearly impossible to find the problem.

**Comment by username7291** [comment] 2020-01-08 10:01
Do it looks similar like in this pictures https://github.com/LibVNC/x11vnc/issues/88 ?

**Comment by PT2020-cd** [comment] 2020-01-08 10:23
Yes, in general it's looking like this. But my screen is much smaller (640x480) and more simple designed. So the number of corrupted rects is much much lower (only 1 or 2 errors).
Also only when using tight encoding and also on ARM structure.
Actually I'm checking for alignment problems in tight.c (ARM has more strict rules like X86) but for now I did not find anything. Also that the problem seems not to exist on a debug build of libvncserver is leading me to this idea.

**Comment by bk138** [comment] 2020-01-08 12:15
Another idea is to play around with the different GCC switches and find the one that is causing this...

**Comment by username7291** [comment] 2020-01-08 14:26
yes corruption is too lower here but the syle is the same. Its working in 0.9.9 and broken with 0.9.11.
I would look at the 64Bit values on ARM if you cant downgrade to 0.9.9

**Comment by PT2020-cd** [comment] 2020-01-15 12:47
The problem is caused on indexed rects when using Tight encoding. Indexed rects are parts of the framebuffer that are encoded with an indexed color table (max 256 colors). The problem is caused by Thread Local Storage defined variables like this (in vncserver/tight.c):

static TLS PALETTE palette;

Somehow the palette.hash field seems to get filled between calling PaletteReset and the first call of PaletteInsert in FastFillPalette32 what may not is possible without multithreading.

When removing the TLS statement the problem does not exist anymore.

The next questions to be clarified now:

Is this (TLS) an ARMv7 (hardware) specific problem?
Is it a compiler bug (arm-linux-gnueabi-gcc 8.3.0 64 bit toolchain for 32 bit ARMv7 code) ?
Is threading used for Tight encoding at all (and when why)?

Any hints from the coders?
I will go on debugging...

**Comment by PT2020-cd** [comment] 2020-01-16 08:39
The more I try debugging the code, the more I realise that the compiler seems to make real bullshit when using TLS (at least IMHO). It's using different memory areas for the same variable even when used in two directly following functions.

FastFillPalette() is calling     

PaletteReset();
PaletteInsert (c0t, (uint32_t)n0, bpp, w); 

directly one after another. Nevertheless in PaletteReset a different memory area is used for
static TLS PALETTE palette;
as it is in PaletteInsert();. IMHO this definitely is the same thread and so it must be the same memory area.

Any suggestions?

**Comment by bk138** [comment] 2020-01-16 08:53
Maybe hackup a minimal sample displaying the issue and send to the compiler guys?

**Comment by PT2020-cd** [comment] 2020-01-16 09:42
The "supporters" for the toolchain are informed and invited to the discussion. I read a bit about TLS and I'm afraid I'm out here. This really seems to be a complicated issue. I'm not even sure if TLS is working on this configuration at all (GCC / ELF / ARMv7). One question to the libvncserver team: Why is there the need to use TLS in tight.c (and some other parts)? I do not see any condition, when two encoding threads may run at the same time (at least in normal usage). Am I wrong?

**Comment by bk138** [comment] 2020-01-16 14:08
>  Why is there the need to use TLS in tight.c (and some other parts)? I do not see any condition, when two encoding threads may run at the same time (at least in normal usage). Am I wrong?

This is in great parts a historic codebase and this might well be not needed anymore...

**Comment by maxnet** [comment] 2021-12-11 19:51
I am also affected by this issue.


I was looking if I could fix that by removing the TLS stuff, and just moving the variables over to struct rfbClientRec, as that seems to be where the other encodings keep their variables for thread safety.
This under the presumption that in multi-threaded mode there would be one thread per client/connection.

However now I see there is a "void rfbTightCleanup (rfbScreenInfoPtr screen)"
https://github.com/LibVNC/libvncserver/blob/master/libvncserver/tight.c#L155
And a "void rfbZlibCleanup(rfbScreenInfoPtr screen)"
https://github.com/LibVNC/libvncserver/blob/master/libvncserver/zlib.c#L63

That also touch the variables that are currently TLS, and they are called once per screen, and not once per client to free memory up when closing down.
Which confuses me.

Is there one thread per screen instead of one per client?!

**Comment by bk138** [comment] 2021-12-11 20:08
> Is there one thread per screen instead of one per client?!

There's 
* [one per screen](https://github.com/LibVNC/libvncserver/blob/master/libvncserver/main.c#L614)
* and two ([output](https://github.com/LibVNC/libvncserver/blob/master/libvncserver/main.c#L455) and [input](https://github.com/LibVNC/libvncserver/blob/master/libvncserver/main.c#L521)) per client

**Closed** 2022-04-10 09:12 UTC
Labels: bug
