### ISSUE TITLE
Any other transport protocol for LibVNC?

### ISSUE THREAD

**Issue by NooshinEghbal** [LibVNC/libvncserver#497] opened 2022-02-03 15:11 UTC
Hi,

I was wondering if LibVNC could run over any other protocols like QUIC/UDT to avoid the Head-of-Line blocking problem of TCP?

Thanks,
Nooshin

**Comment by NooshinEghbal** [comment] 2022-02-03 21:27
Thanks.
I looked into multicastvnc/libvncserver/sockets.c and found where the UDP socket created. 
But I could not find how you managed reliability using UDP. In other words, in the case of packet loss, how you know to resend it?

**Comment by bk138** [comment] 2022-02-04 08:47
> Thanks. I looked into multicastvnc/libvncserver/sockets.c and found where the UDP socket created. But I could not find how you managed reliability using UDP. In other words, in the case of packet loss, how you know to resend it?

There's an overview [here](https://github.com/LibVNC/libvncserver/blob/multicastvnc/MulticastVNCProto.txt) and an in-depth discussion [here](https://edoc.hu-berlin.de/bitstream/handle/18452/14818/beier.pdf?sequence=1&isAllowed=y)

**Comment by RokerHRO** [comment] 2022-02-04 14:07
> But I could not find how you managed reliability using UDP. In other words, in the case of packet loss, how you know to resend it?

It is the very nature of UDP that packets can be lost without the whole system would collaps. And multicast also does not allow re-sending to individual recepients, because the server does not know who listens to it.

In other words: The chosen odecs must be fault tolerant, fit into one UDP packet and I'd say also more often non-incremental screen updates might be necessary to recover quickly from display artifacts caused by loss packets.

I'd favour VNC-over-RTP, so also an RTCP channel exists where clients can report "channel quality" information back to the server.

**Comment by bk138** [comment] 2023-11-11 19:22
Let's consider this a dupe of #394 (which has some fault tolerance built into it).

**Closed by bk138** 2023-11-11 19:22 UTC
Labels: feature-request
