### ISSUE TITLE
vncserver crashed when vncclient connected

### ISSUE THREAD

**Issue by itsmypink** [LibVNC/libvncserver#358] opened 2019-12-18 11:00 UTC
I run vncserver with simple.exe
server is waiting for connections on port 5900
Then,  I run VncViewer and connect
VncViewer pop-up error: RFB rptocol error bad desktop size 36865*11265
and simple.exe crashed:
Expression:(fh>=0&&(unsigned)fh<(unsigned)_nhandle)

I have no idea about this ,and not sure if it is bug ?

system:windows7 64bit

**Comment by bk138** [comment] 2019-12-18 11:26
dupe of #165

**Closed by bk138** 2019-12-18 11:26 UTC
Labels: bug, platform-windows

**Comment by bk138** [comment] 2019-12-18 11:33
dupe of #329
