### ISSUE TITLE
Size issue and crash on Windows

### ISSUE THREAD

**Issue by BastiaanOlij** [LibVNC/libvncserver#216] opened 2018-01-28 02:33 UTC
Running any of the server examples and trying to connect to them with RealVNC Viewer I get a "RFB protocol error: bad desktop size" followed by a weirdly high resolution value. The example program subsequently crashes.

This is running Windows 10 using Microsoft Visual Studio 2017 and CMake 3.10

**Comment by sfhacker** [comment] 2018-04-15 11:56
Has this long standing issue been fixed? How can I reproduce this app crash?

**Comment by jeilun** [comment] 2019-04-06 17:48
@sfhacker 
I have the same problem when I try to connect from vnc viewer .
client error : rfb protocol error  bad desktop size
server error : returning securityresult for client rfb >= 3.8

![virtual](https://user-images.githubusercontent.com/3160679/55673161-55038980-58b9-11e9-8c7d-1639d8a64192.jpg)

![host](https://user-images.githubusercontent.com/3160679/55673169-71072b00-58b9-11e9-97e5-abee12b92dc4.jpg)

**Comment by RubberFeng** [comment] 2019-08-08 06:00
> @sfhacker
that error of vcruntime,about "close.cpp",I have fix it,look the newest issue.It's server's bug when client closed connection.
But I don't also have the save problem about size'crash.It's a weirdly high resolution value.and I try to change the resolution to 1x1,the error tips change to "String exceed maximum...."!~~Who can fix this problem ,please help!

**Comment by bk138** [comment] 2020-01-09 21:21
The close.cpp thing is a dupe of #329 . The other issue might have been fixed by #353, please check.

**Comment by bk138** [comment] 2020-01-30 22:12
Tentatively closing, please re-open if issue persists!

**Closed by bk138** 2020-01-30 22:12 UTC
Labels: bug, platform-windows, response-needed

**Comment by nishant4uster1** [comment] 2021-06-11 15:41
I got "RFB protocol error: bad desktop size 0x0 " and Apple PC restart, worked for me.
