### ISSUE TITLE
VNC Viewer- String exceed maximum length ; Debug assertion failed

### ISSUE THREAD

**Issue by DaburLal** [LibVNC/libvncserver#200] opened 2017-10-19 14:21 UTC
i tried running example.exe and simple.exe on my windows 7, 64 bit PC but following errors i am getting.

1- Viewer says string exceeds maximum length 
2- While debugging as the viewer tries to connect i get Debug assertion failed and when i stop it , it gives this :simple.exe has triggered a breakpoint. occurred.

![unbenannt](https://user-images.githubusercontent.com/32668117/31775649-8448ba28-b4e9-11e7-8263-400fa64b3792.PNG)

**Comment by bk138** [comment] 2020-01-11 15:00
Looks like a dupe of #329. If not, please re-open this issue!

**Closed by bk138** 2020-01-11 15:00 UTC
Labels: bug, platform-windows
