### ISSUE TITLE
websockets: I can't get pass the GET header checking when using https connection

### ISSUE THREAD

**Issue by kayechica** [LibVNC/libvncserver#332] opened 2019-08-22 07:09 UTC
Hello.

I am still using LibVNCServer-0.9.11 and I have the following problems.
I always get an error "webSocketsHandshake: invalid client header" every time I use HTTPS connection. If I use HTTP, everything is OK.

Because of this, I commented out the following codes for now inside webSocketsCheck() in websockets.c:

    if (strncmp(bbuf, "GET ", 4) != 0) {
      rfbErr("webSocketsHandshake: invalid client header\n");
      return FALSE;
    }

After commenting it out, it went ahead the handshake process and the receiving of the protocol version, but then got stuck inside webSocketsDecodeHybi() because of these codes:

    ret = ws_peek(cl, buf, B64LEN(len) + WSHLENMAX);

    if (ret < 2) {
        /* save errno because rfbErr() will tamper it */
        if (-1 == ret) {
            int olderrno = errno;
            rfbErr("%s: peek; %m\n", __func__);
            errno = olderrno;
        } else if (0 == ret) {
            result = 0;
        } else {
            errno = EAGAIN;
        }
        goto spor;
    }

The problem here is that when I use HTTPS connection, the value of ret is always 1 (because of the return of SSL_peek which is just 1 byte) so it always exits the function and disconnects it.

Is there a configuration that I miss?
Is it normal to always get the value 1 when SSL_peek is used?
I have been trying to solve this for a couple of weeks now, can someone please enlighten me.

Thanks.

**Comment by kayechica** [comment] 2019-08-22 09:16
Additional info:

`
    } else if (strncmp(bbuf, "\x16", 1) == 0 || strncmp(bbuf, "\x80", 1) == 0) {
        rfbLog("Got TLS/SSL WebSockets connection\n");
        if (-1 == rfbssl_init(cl)) {
	  rfbErr("webSocketsHandshake: rfbssl_init failed\n");
	  return FALSE;
	}
	ret = rfbPeekExactTimeout(cl, bbuf, 4, WEBSOCKETS_CLIENT_CONNECT_WAIT_MS);
        scheme = "wss";
    } else {
        scheme = "ws";
    }
`
After this log message: "Got TLS/SSL WebSockets connection" during webSocketsCheck(),
rfbssl_init() went well using the init function inside rfb_openssl.c

Then during rfbPeekExactTimeout(), it will perform rfbssl_peek()
This always returns 1 with errno value set to 0 (zero).
Since errno is 0, it exits the function and cannot reach the call to rfbssl_pending().

I cannot use the new libvncserver version since I am working on an old project with limits like cmake  version 2.8.11 and openssl 0.9.8.

**Comment by bk138** [comment] 2019-08-27 16:17
Maybe this got fixed in a newer LibVNCServer version - have you tried?

**Comment by kayechica** [comment] 2019-08-28 01:38
_I cannot use the new libvncserver(0.9.12) version since I am working on an old project with limits like cmake version 2.8.11 and openssl 0.9.8._

For some reason, I always get 1 as a return value for SSL_peek (in ws_peek).
I never get a value greater than 1. Is that a weird behavior?

That's why I always "goto spor" in these codes: webSocketsDecodeHybi()

ret = ws_peek(cl, buf, B64LEN(len) + WSHLENMAX);

if (ret < 2) {
    /* save errno because rfbErr() will tamper it */
    if (-1 == ret) {
        int olderrno = errno;
        rfbErr("%s: peek; %m\n", __func__);
        errno = olderrno;
    } else if (0 == ret) {
        result = 0;
    } else {
        errno = EAGAIN;
    }
    goto spor;
}

I tried to look in to other issues inside libvncserver but I cannot see a similar issue like mine.
Is there a setup needed to correctly use SSL in libvncserver?
I am also using the noVNC client packaged with this libvncserver 0.9.11.

**Comment by bk138** [comment] 2020-03-12 20:32
Please try with current master to see if the issue is in there as well.

**Comment by bk138** [comment] 2020-04-11 09:07
Tentatively closing, please re-open if issue persists.

**Closed by bk138** 2020-04-11 09:07 UTC
Labels: bug, response-needed

**Comment by lagurus** [comment] 2023-10-19 09:21
I had the same problem but it seems it was all caused by a self signed certificate that secure WebSocket didn't want to
accept in the browser.

The solution for me was to go to https://localhost:5900 (browse normally to the websocket port) and accept the certificate.
