### ISSUE TITLE
crash in gnutls_certificate_set_x509_key_file2()

### ISSUE THREAD

**Issue by nlsmart** [LibVNC/libvncserver#303] opened 2019-05-08 06:07 UTC
Hi,

First, congratulation for your work !

Please find 3 bugs reports, a kde dev advise me to send you those reports.
I sent it to gnutls.

find below a link with some details post on the Kde forum :

https://bugs.kde.org/show_bug.cgi?id=407206

find below the 3 bugs reports

[krfb-20190415-114613.kcrash.txt](https://github.com/LibVNC/libvncserver/files/3155735/krfb-20190415-114613.kcrash.txt)
[krfb-20190422-005644.kcrash.txt](https://github.com/LibVNC/libvncserver/files/3155738/krfb-20190422-005644.kcrash.txt)
[krfb-20190503-083309.kcrash.txt](https://github.com/LibVNC/libvncserver/files/3155740/krfb-20190503-083309.kcrash.txt)

with best regards,

**Comment by bk138** [comment] 2019-05-09 19:44
Related to #280 or #219?

**Comment by bk138** [comment] 2019-05-09 19:45
@nlsmart are you able to provide symbolicated backtraces, i.e. use debug builds that don't have debug symbols stripped, esp. libgnutls?

**Comment by bk138** [comment] 2019-05-09 20:14
Dupe of #219

**Closed by bk138** 2019-05-09 20:14 UTC
Labels: bug
